export const USER_ACTION_TYPES = {
  FETCH_CURRENT_USER_START: "user/FETCH_CURRENT_USER_START",
  FETCH_CURRENT_USER_SUCCESS: "user/FETCH_CURRENT_USER_SUCCESS",
  FETCH_CURRENT_USER_FAILED: "user/FETCH_CURRENT_USER_FAILED",
};
